/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedGameNewRouteImport } from './routes/_authed/game.new'
import { Route as AuthedGameIdRouteImport } from './routes/_authed/game.$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGameNewRoute = AuthedGameNewRouteImport.update({
  id: '/game/new',
  path: '/game/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGameIdRoute = AuthedGameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof SignInRoute
  '/game/$id': typeof AuthedGameIdRoute
  '/game/new': typeof AuthedGameNewRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/': typeof AuthedIndexRoute
  '/game/$id': typeof AuthedGameIdRoute
  '/game/new': typeof AuthedGameNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/game/$id': typeof AuthedGameIdRoute
  '/_authed/game/new': typeof AuthedGameNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/game/$id' | '/game/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/' | '/game/$id' | '/game/new'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/_authed/'
    | '/_authed/game/$id'
    | '/_authed/game/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/game/new': {
      id: '/_authed/game/new'
      path: '/game/new'
      fullPath: '/game/new'
      preLoaderRoute: typeof AuthedGameNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/game/$id': {
      id: '/_authed/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof AuthedGameIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedGameIdRoute: typeof AuthedGameIdRoute
  AuthedGameNewRoute: typeof AuthedGameNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedGameIdRoute: AuthedGameIdRoute,
  AuthedGameNewRoute: AuthedGameNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
